# Generated by Django 2.2.5 on 2023-02-13 07:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0005_auto_20191005_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBotAdmin',
            new_name='Users',
        ),
    ]
