# Generated by Django 2.2.5 on 2023-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_accountheads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountheads',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
