# Generated by Django 2.2.5 on 2023-02-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountHeads',
            new_name='AccountHeadss',
        ),
    ]
