# Generated by Django 2.2.5 on 2023-02-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20230213_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountHeadss',
            new_name='AccountHeads',
        ),
    ]
