# Generated by Django 2.2.5 on 2023-02-14 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_auto_20230213_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 14)),
        ),
    ]
