# Generated by Django 2.2.5 on 2023-02-14 06:56

import basic_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20230214_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='credit',
            field=models.IntegerField(default=0, validators=[basic_app.models.credit]),
        ),
        migrations.AlterField(
            model_name='records',
            name='debit',
            field=models.IntegerField(default=0, validators=[basic_app.models.creditDebitValidator]),
        ),
    ]
