# Generated by Django 2.2.5 on 2023-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_auto_20230214_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='accountheads',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='accountheads',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
