# Generated by Django 2.2.5 on 2023-02-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_auto_20230215_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
